<a href="https://colab.research.google.com/github/triveni0316/Projects/blob/main/neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [81]:
import numpy as np

In [82]:
#assigning input values
input_value = np.array([[0,0],[0,1],[1,1],[1,0]])
input_value.shape
input_value

array([[0, 0],
       [0, 1],
       [1, 1],
       [1, 0]])

In [83]:
#assigning output values
output = np.array([0,1,1,0])
output = output.reshape(4,1)
output.shape

(4, 1)

In [84]:
#assign weights
weight = np.array([[0.1],[0.2]])
weight

array([[0.1],
       [0.2]])

In [85]:
#adding bias
bias = 0.3

In [86]:
#activation function
def sigmoid_function(x):
  return 1/(1 + np.exp(-x))

In [87]:
#derivative of sigmoid function
def der(x):
  return sigmoid_function(x) * (1- sigmoid_function(x))

In [94]:
#updating weights
for epochs in range(10000):
  input_arr = input_value

  weighted_sum = np.dot(input_arr, weight)+bias
  first_output = sigmoid_function(weighted_sum)

  error = first_output-output
  total_error = np.square(np.subtract(first_output, output)).mean()
  #print(total_error)

  first_der = error
  second_der = der(first_output)
  derivative = first_der * second_der

  t_input=input_value.T
  final_derivative = np.dot(t_input, derivative)

  #update weights
  weight = weight - 0.05 * final_derivative

  #update bias
  for i in derivative:
    bias = bias - 0.05 * i

print(weight)
print(bias)


[[-0.41083034]
 [11.80234455]]
[-5.61173501]


In [95]:
#predictions
pred = np.array([0,1])

result = np.dot(pred, weight) + bias

res = sigmoid_function(result)

print(res)

[0.99795561]
